name: RetrieverMCPvP
description: PvP
author: MintyCodes
main: me.admin.retrieverpvp.Core
version: Development

commands:
    pvphelp:
      description: Displays the Help Message for PvP
      usage: /<command>
    pvpchallenge:
      description: Challenge a Player!
      usage: /<command>
    pvpsetspawn:
      description: Sets Spawn
      usage: /<command>
    pvpdelspawn:
      description: Deletes Spawn
      usage: /<command>
    pvpteleport:
      description: Teleports the player
      usage: /<command>
      
permissions:
    retrieverpvp.pvphelp:
      default: op
      description: Allows access to /pvphelp
    retrieverpvp.pvpchallenge:
      default: op
      description: Allows access to /pvpchallenge
    retrieverpvp.setspawn:
      default: op
      description: Set Spawn
    retrieverpvp.delspawn:
      default: op
      description: Delete Spawn
    retrieverpvp.teleport:
      default: op
      description: Base teleport command
    retrieverpvp.teleport.others:
      default: op
      description: Teleport others command